apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventgallery-backend
  namespace: eventgallery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eventgallery-backend
  template:
    metadata:
      labels:
        app: eventgallery-backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/noluchs/sem4-eventgallery/eventgallery-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: SQLALCHEMY_DATABASE_URI
              value: "mysql://root:rootpassword@eventgallery-db:3306/eventgallery"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20