apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventgallery-backend
  namespace: eventgallery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eventgallery-backend
  template:
    metadata:
      labels:
        app: eventgallery-backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/noluchs/sem4-eventgallery/eventgallery-backend:54e97156a4ff7e6582b3e85894aa3424e6fe739e
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_URI
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DATABASE_URI
            - name: CHOKIDAR_USEPOLLING
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: CHOKIDAR_USEPOLLING
            - name: FLASK_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: FLASK_DEBUG
            - name: FLASK_RUN_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: FLASK_RUN_HOST
            - name: FLASK_RUN_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: FLASK_RUN_PORT
            - name: FLASK_APP
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: FLASK_APP
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: MYSQL_USER
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: AWS_REGION
            - name: S3_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: S3_BUCKET
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: SECRET_KEY
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: S3_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: S3_KEY
            - name: S3_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: S3_SECRET
            - name: AWS_REKOGNITION_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: AWS_REKOGNITION_KEY
            - name: AWS_REKOGNITION_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: AWS_REKOGNITION_SECRET
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: eventgallery
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: eventgallery-backend
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70