apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: eventgallery
data:
  DATABASE_URI: "mysql+pymysql://root:root@eventgallery-db:3306/eventgallery"
  CHOKIDAR_USEPOLLING: "true"
  FLASK_DEBUG: "1"
  FLASK_RUN_HOST: "0.0.0.0"
  FLASK_RUN_PORT: "5000"
  FLASK_APP: "app"
  MYSQL_DATABASE: "eventgallery"
  MYSQL_USER: "eventgallery"
  AWS_REGION: "eu-central-1"
  S3_BUCKET: "msvc-gallery"