apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: eventgallery
  namespace: argocd
spec:
  destinations:
    - namespace: eventgallery
      server: https://kubernetes.default.svc
  sourceRepos:
    - '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'