apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventgallery-frontend
  namespace: eventgallery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eventgallery-frontend
  template:
    metadata:
      labels:
        app: eventgallery-frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/noluchs/sem4-eventgallery/eventgallery-frontend:fae56a4cda21532110029b807295470ddc9004f1
          ports:
            - containerPort: 3000
          env:
            - name: BACKEND_URL
              value: "http://eventgallery-backend:5000"
          resources:
            requests:
              memory: "128Mi"
              cpu: "125m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
  namespace: eventgallery
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: eventgallery-frontend
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 70
