apiVersion: v1
kind: Service
metadata:
  name: eventgallery-db
  namespace: eventgallery
spec:
  selector:
    app: eventgallery-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP