apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: eventgallery
  namespace: argocd
  labels:
    app.kubernetes.io/instance: eventgallery
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: eventgallery
    server: https://kubernetes.default.svc
  - namespace: argocd
    server: https://kubernetes.default.svc
  sourceRepos:
  - '*'