name: Backend CI/CD Pipeline

on:
  push:
    paths:
      - 'code/backend/**'
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          cd code/backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run tests
        id: tests
        continue-on-error: true
        run: |
          cd code/backend
          python -m pytest
          
      - name: Notify test failures
        if: steps.tests.outcome == 'failure'
        run: |
          echo "::warning ::Tests failed but continuing with deployment"

  package-and-push:
    needs: build-and-test
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push backend Docker image
        run: |
          REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          docker buildx build --platform linux/amd64 \
            -t ghcr.io/$REPO_NAME/eventgallery-backend:latest \
            -t ghcr.io/$REPO_NAME/eventgallery-backend:${{ github.sha }} \
            -f ./code/backend/Dockerfile ./code/backend --push

  update-k8s:
    needs: package-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update K8s manifests
        run: |
          REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          sed -i "s|ghcr.io/$REPO_NAME/eventgallery-backend:.*|ghcr.io/$REPO_NAME/eventgallery-backend:${{ github.sha }}|" infrastructure/k8s/backend-deployment.yaml
      
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add infrastructure/k8s/backend-deployment.yaml
          git commit -m "Update backend deployment image to ${{ github.sha }}"
          git push