name: Build and Deploy
on:
  push:
    branches: 
      - main
env:
  IMAGE_TAG: ${{ github.sha }}
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push backend Docker image
        run: |
          REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          docker buildx build --platform linux/amd64 \
            -t ghcr.io/$REPO_NAME/eventgallery-backend:latest \
            -t ghcr.io/$REPO_NAME/eventgallery-backend:${{ env.IMAGE_TAG }} \
            -f ./code/backend/Dockerfile.prod ./code/backend --push

      - name: Build and push frontend Docker image 
        run: |
          REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          docker buildx build --platform linux/amd64 \
            -t ghcr.io/$REPO_NAME/eventgallery-frontend:latest \
            -t ghcr.io/$REPO_NAME/eventgallery-frontend:${{ env.IMAGE_TAG }} \
            -f ./code/frontend/Dockerfile.prod ./code/frontend --push

      - name: Update Kubernetes manifests
        run: |
          REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          # Update backend deployment
          sed -i "s|ghcr.io/$REPO_NAME/eventgallery-backend:.*|ghcr.io/$REPO_NAME/eventgallery-backend:${{ env.IMAGE_TAG }}|" infrastructure/k8s/backend-deployment.yaml
          # Update frontend deployment  
          sed -i "s|ghcr.io/$REPO_NAME/eventgallery-frontend:.*|ghcr.io/$REPO_NAME/eventgallery-frontend:${{ env.IMAGE_TAG }}|" infrastructure/k8s/frontend-deployment.yaml

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add infrastructure/k8s/backend-deployment.yaml infrastructure/k8s/frontend-deployment.yaml
          git commit -m "Update deployment images to ${{ env.IMAGE_TAG }}"
          git push