name: CI/CD Pipeline

on:
  push:
    paths:
      - 'code/**'
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push frontend Docker image
        run: |
          REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          docker buildx build --platform linux/amd64 -t ghcr.io/$REPO_NAME/eventgallery-frontend:latest -f ./code/frontend/Dockerfile.prod ./code/frontend --push

      - name: Build and push backend Docker image
        run: |
          REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          docker buildx build --platform linux/amd64 -t ghcr.io/$REPO_NAME/eventgallery-backend:latest -f ./code/backend/Dockerfile.prod ./code/backend --push