name: Frontend CI/CD Pipeline

on:
  push:
    paths:
      - 'code/frontend/**'
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: cd code/frontend && npm install
        
      - name: Run tests
        run: cd code/frontend && npm test

  package-and-push:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push frontend Docker image
        run: |
          REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          docker buildx build --platform linux/amd64 \
            -t ghcr.io/$REPO_NAME/eventgallery-frontend:latest \
            -t ghcr.io/$REPO_NAME/eventgallery-frontend:${{ github.sha }} \
            -f ./code/frontend/Dockerfile.prod ./code/frontend --push

  update-k8s:
    needs: package-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update K8s manifests
        run: |
          REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          sed -i "s|ghcr.io/$REPO_NAME/eventgallery-frontend:.*|ghcr.io/$REPO_NAME/eventgallery-frontend:${{ github.sha }}|" infrastructure/k8s/frontend-deployment.yaml

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add infrastructure/k8s/frontend-deployment.yaml
          git commit -m "Update deployment images to ${{ github.sha }}"
          git push